[PHP]
memory_limit = 128M
upload_max_filesize = 10M
post_max_size = 10M
max_execution_time = 60
max_input_time = 60

[opcache]
opcache.enable = 1
opcache.memory_consumption = 32
opcache.interned_strings_buffer = 2
opcache.max_accelerated_files = 2000
opcache.revalidate_freq = 2
opcache.fast_shutdown = 1
